### ISSUE TITLE
Доработка DC

### ISSUE THREAD

**Issue by sh0ked** [2gis/contesto#22]
- если указан browser, то берём дефолтные DC для этого браузера
- если браузера нет, то делаем их пустым словарём (или какими-нибудь ещё дефолтными для всяких там qtwebkitdriver)
- если есть DC в кофигне, то обновить DC переданными (что-то типа dict.update будет)
- никакие другие параметры не должны попадать в DC
- в DC для vmmaster имя сессии добавлять

**Comment by nwlunatic** [comment]
https://github.com/2gis/contesto/pull/45
