### ISSUE TITLE
В Python3 нет поддержки __metaclass__

### ISSUE THREAD

**Issue by MihaylovNikitos** [2gis/contesto#66]
В Python3 нет поддержки __metaclass__:
https://github.com/2gis/contesto/blob/master/contesto/basis/component.py#L12

Теперь пишется это так:
```python
class Component(LoadableObject, metaclass = AutoExtendingSelectors)
```

Падает куча тестов, где предопределяется selectors, н-р:
[test_address_in_building_with_title](https://github.com/2gis/online4/blob/c134a6ba4265a74eb796b7540cb96687b37c63ea/functional-tests/tests/map/building_callout.py#L87)
[test_firm_view_in_callout](https://github.com/2gis/online4/blob/c134a6ba4265a74eb796b7540cb96687b37c63ea/functional-tests/tests/map/building_callout.py#L112)

Ошибка при этом:
```
Traceback (most recent call last):
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/lode_runner/plugins/initializer.py", line 18, in wrapper
    result = test(*args, **kwargs)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/lode_runner/plugins/dataprovider.py", line 254, in <lambda>
    standalone_func = lambda *args: func(*(args + data_set))
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/tests/map/building_callout.py", line 122, in test_firm_view_in_callout
    callout_firms = self.page.map.building_callout.firms_titles
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/classes/components/map/map.py", line 199, in building_callout
    return BuildingCallout(self.test, self.element.find_element_by_css_selector(BuildingCallout.selectors['self']))
KeyError: 'self'
```

**Comment by NickAb** [comment]
А у вас в проекте разве не python 2 используют? В файле https://github.com/2gis/online4/blob/c134a6ba4265a74eb796b7540cb96687b37c63ea/functional-tests/install_linux.sh, например, ставят пакет python-pip, сам python не ставят, значит берут системный, а системный – python2. Да и python-pip – pip для второго питона.

**Comment by NickAb** [comment]
https://github.com/2gis/contesto/blob/09bdd0534dfbba0e344d3c3f588f2b03ba403452/contesto/basis/component.py#L11-L12

Можно использовать six, см. https://pythonhosted.org/six/#six.with_metaclass
А можно отказаться от этого метакласса вообще и перейти на определение локаторов как полей класса. Это кажется более правильным вариантам, т.к. тогда:
1. пропадает этот хак с наследованием словарей
2. в коде начинают работать подсказки по именам полей-локаторов
3. не надо тянуть six
4. код становится легче понять

**Comment by MihaylovNikitos** [comment]
Да в python 2 все ок. Проблема будет если перейти на python 3.) 
Спасибо за советы, надо об этом подумать. + мы знаем костыль, для решение это проблемы.

**Comment by NickAb** [comment]
Какой костыль и зачем? Почему не избавиться от словарей selectors?

Github нашел всего 76 результатов https://github.com/2gis/online4/search?l=python&p=1&q=selectors&utf8=%E2%9C%93

Кажется это не так сложно исправить, при этом не нужны костыли.

**Comment by MihaylovNikitos** [comment]
У себя, при наследовании от компонента, написать metaclass. Это решение вроде не костыль, а вроде и чуть-чуть костыль.

Не не сложно, подумаем над вариантами. А сейчас это не горит)
